---

- name: 'upgrade all packages'
  dnf:
    name: "*"
    state: latest

- name: 'install OBS k8s repo'
  command:
    cmd: dnf config-manager --add-repo https://download.opensuse.org/repositories/home:anthr76:kubernetes/openSUSE_Tumbleweed/home:anthr76:kubernetes.repo
    warn: false
  args:
    creates: /etc/dnf/repos.d/home:anthr76:kubernetes.repo

- name: 'install OBS repo'
  command:
    cmd: dnf config-manager --add-repo https://download.opensuse.org/repositories/home:anthr76/openSUSE_Tumbleweed/home:anthr76.repo
    warn: false
  args:
    creates: /etc/dnf/repos.d/home:anthr76.repo

- name: 'install packages'
  dnf:
    name:
      - neovim
      - flux
      - osc
      - doctl
      - kind
      - k9s
      - kubernetes-client
      - kuberlr
      - helm
      - go
      - python38-pre-commit
      - gh
      - terraform
      - flatpak-xdg-utils
      - rpmlint
      - dirmngr
      - libopenssl1_0_0
      - gnome-keyring
