---
verifyConditions:
  - "@semantic-release/github"
prepare: false
publish:
  - "@semantic-release/github"
success: false
fail: false
npmPublish: false
branches:
  - "main"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"