---

- name: 'upgrade all packages' # noqa package-latest
  dnf:
    name: "*"
    state: latest
    update_cache: true
    skip_broken: true

- name: 'install OBS k8s repo'
  command:
    cmd: dnf config-manager --add-repo https://download.opensuse.org/repositories/home:anthr76:kubernetes/openSUSE_Tumbleweed/home:anthr76:kubernetes.repo
    warn: false
  args:
    creates: /etc/dnf/repos.d/home:anthr76:kubernetes.repo

- name: 'install OBS repo'
  command:
    cmd: dnf config-manager --add-repo https://download.opensuse.org/repositories/home:anthr76/openSUSE_Tumbleweed/home:anthr76.repo
    warn: false
  args:
    creates: /etc/dnf/repos.d/home:anthr76.repo

- name: 'install GNOME OBS repo'
  command:
    cmd: dnf config-manager --add-repo https://download.opensuse.org/repositories/GNOME:Next/openSUSE_Factory/GNOME:Next.repo
    warn: false
  args:
    creates: /etc/dnf/repos.d/home:anthr76.repo

- name: 'install packages' # noqa package-latest
  dnf:
    name:
      - neovim
      - flux
      - osc
      - doctl
      - kind
      - k9s
      - kubernetes-client
      - kuberlr
      - helm
      - go
      - python38-pre-commit
      - gh
      - terraform
      - flatpak-xdg-utils
      - rpmlint
      - dirmngr
      - libopenssl1_0_0
      - gnome-keyring
      - python3-yamllint
      - npm
      - python3-pip
      - task
      - ShellCheck
    state: latest
    skip_broken: true
    # allowerasing: true ansible 2.10

- name: 'install npm packages'
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: latest
  loop:
    - 'prettier'
    - '@bitwarden/cli'

- name: 'install pip stuff'
  pip:
    name: "{{ item }}"
  loop:
    - 'ansible-lint'
