---

- name: 'get home directory'
  ansible.builtin.setup:
    gather_subset:
    filter: ansible_user_dir
  become: false

- name: 'ensure flatpak nameConfigs directory exists'
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.var/app/com.visualstudio.com/config/Code/User/globalStorage/ms-vscode-remote.remote-containers/nameConfigs/'
    state: directory

- name: 'provision flatpak vs-code to use with toolbox container'
  ansible.builtin.copy:
    src: files/{{ toolbox_container_name }}.json
    dest: '{{ ansible_user_dir }}/.var/app/com.visualstudio.com/config/Code/User/globalStorage/ms-vscode-remote.remote-containers/nameConfigs/{{ toolbox_container_name }}.json'
  become: false

- name: 'avoid breaking host gitconfig'
  ansible.builtin.copy:
    src: files/settings.json
    dest: /root/.vscode-server/data/Machine/settings.json