FROM docker.io/library/archlinux:base-20210509.0.21942

ENV NAME=archlinux-toolbox VERSION=base
LABEL com.github.containers.toolbox="true" \
      com.github.debarshiray.toolbox="true" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating Arch Linux toolbox containers" \
      maintainer="Anthony Rabbito <hello@anthonyrabbito.com>" \
      org.opencontainers.image.source="https://github.com/anthr76/tooling"

COPY extra-packages /
RUN pacman -Syu --needed --noconfirm - < extra-packages
RUN rm /extra-packages

RUN mkdir /etc/sudoers.d/ && echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/toolbox
RUN touch /etc/machine-id

RUN pacman -Scc --noconfirm

CMD /bin/sh
