FROM docker.io/library/archlinux@sha256:339ce5aad19cb7bb40cfbb171504fca2622fef754282ceb8f945b60b2fb7b728

ENV NAME=archlinux-toolbox VERSION=base
LABEL com.github.containers.toolbox="true" \
      com.github.debarshiray.toolbox="true" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="You should not use this container and instead use your own customizations on a fork" \
      maintainer="Anthony Rabbito <hello@anthonyrabbito.com>"

COPY host-runner /usr/libexec/toolbox/host-runner
COPY podman-host.sh /usr/libexec/toolbox/podman-host.sh
COPY pkgs.arch /opt/pkgs
COPY 01-shim.sh /etc/profile.d/01-shim.sh
COPY extra-packages /

RUN \
    bash -c "pacman --noconfirm -Syu && \
    pacman -Syu --needed --noconfirm - < extra-packages && \
    rm /extra-packages && \
    mkdir /etc/sudoers.d/ && echo \x22%wheel ALL=(ALL) NOPASSWD: ALL\x22 > /etc/sudoers.d/toolbox && \
    touch /etc/machine-id && \
    pacman --noconfirm -S curl zsh neovim && \
    ls /usr/libexec/toolbox && \
    chmod +x /usr/libexec/toolbox/host-runner && \
    chmod 444 /opt/pkgs && \
    chmod +x /usr/libexec/toolbox/podman-host.sh && \
    ln -s /usr/libexec/toolbox/host-runner /usr/libexec/toolbox/flatpak && \
    ln -s /usr/libexec/toolbox/host-runner /usr/libexec/toolbox/virsh && \
    ln -s /usr/libexec/toolbox/podman-host.sh /usr/libexec/toolbox/podman && \
    ln -s /usr/libexec/toolbox/host-runner /usr/libexec/toolbox/skopeo && \
    ln -s /usr/libexec/toolbox/host-runner /usr/libexec/toolbox/buildah && \
    ln -s /usr/libexec/toolbox/host-runner /usr/libexec/toolbox/virt-install && \
    pacman -S --noconfirm --needed reflector base-devel git asp && \
    useradd -g wheel -d /home/makepkg makepkg && \
    mkdir -p /home/makepkg/{.config/pacman,.gnupg,out} && \
    echo 'MAKEFLAGS=\x22-j$(nproc)\x22' >> /home/makepkg/.config/pacman/makepkg.conf && \
    echo 'PKGDEST=\x22/home/makepkg/out\x22' >> /home/makepkg/.config/pacman/makepkg.conf && \
    echo 'keyserver-options auto-key-retrieve' > /home/makepkg/.gnupg/gpg.conf && \
    chown -R makepkg:wheel /home/makepkg && \
    sudo -u makepkg git clone https://aur.archlinux.org/paru-bin.git /home/makepkg/paru && \
    cd /home/makepkg/paru && \
    sudo -u makepkg makepkg --noconfirm -si && \
    sudo -u makepkg makepkg --printsrcinfo > .SRCINFO && \
    cat .SRCINFO && \
    mv .SRCINFO /opt/paru.SRCINFO && \
    cd / && \
    userdel makepkg && \
    rm -rf /root && rm -rf /home/makepkg && \
    mkdir /root && \
    chmod -R 777 /root && \
    pacman -Scc --noconfirm"

CMD ["/bin/sh"]

LABEL org.opencontainers.image.source https://github.com/anthr76/tooling
