#!/bin/bash 
# https://github.com/containers/toolbox/issues/145
executable=$(basename "$0")
set -x
exec flatpak-spawn --host --watch-bus --forward-fd=1 --forward-fd=2 --directory="$(pwd)" --env=TERM=xterm-256color "$executable" "$@"