---

name: toolbox build
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    name: build toolbox image
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64 ]
        # arch currently only published x86. Since other arch's is not needed we won't build our own.

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - run: |
       sudo apt-get install fuse-overlayfs
       mkdir -vp ~/.config/containers
       printf "[storage.options]\nmount_program=\"/usr/bin/fuse-overlayfs\"" > ~/.config/containers/storage.conf

    - name: get git short hash
      run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
    
    - name: setup multi-arch builds
      run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2.7
      with:
        image: tooling
        tags: ${{ env.SHORT_SHA }}
        oci: true
        arch: ${{ matrix.arch }}
        context: images/shim
        dockerfiles: ./images/shim/Containerfile

