name: container-pull-request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        id: build
        uses: redhat-actions/buildah-build@v2.8
        with:
         image: boombox
         tags: ${{github.event.number}}
         oci: true
         layers: true
         containerfiles: ./Containerfile
         extra-args: |
           --squash