name: container-pull-request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
       include:
         - containerfile: Containerfile
           image: "boombox"
         - containerfile: Containerfile-arch
           image: "boombox-arch"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        id: build
        uses: redhat-actions/buildah-build@v2.7
        with:
         image: ${{ matrix.image }}
         tags: ${{github.event.number}}
         oci: true
         layers: true
         containerfiles: ./${{ matrix.containerfile }}
         extra-args: |
           --squash
