name: container-release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=version::${GITHUB_REF##*/}

      - name: Build
        id: build
        uses: redhat-actions/buildah-build@v2.7
        with:
         image: boombox
         tags: v${{ steps.prep.outputs.version }} latest
         oci: true
         layers: true
         containerfiles: ./Containerfile
         extra-args: |
           --squash
        
      - name: Push
        uses: redhat-actions/push-to-registry@v2.3.2
        with:
         image: ${{ steps.build.outputs.image }}
         tags:  ${{ steps.build.outputs.tags }}
         registry: ghcr.io/${{ github.actor }}
         username: ${{ github.actor }}
         password: ${{ secrets.CR_TOKEN }}
